//! Item identity: bundled brand marks, user-supplied icons, and the generated shape
//! that stands in for the rest (ADD-001).
//!
//! ADD-001 is the strongest privacy rule in the product after the no-network rule
//! itself:
//!
//! > Every runtime favicon fetch — direct from the site, or through a third-party
//! > favicon service — announces to an observer that this user holds an account with
//! > that service. Do it for every item and you have transmitted, in the clear, a
//! > complete inventory of the user's accounts.
//!
//! The design prototype fetches `google.com/s2/favicons`, and this module is what
//! replaces it. **There is no URL construction anywhere in this file.** Grep it: the
//! only things that leave here are an icon *key* naming a file inside our own bundle,
//! and integers.
//!
//! ## Resolution order
//!
//! 1. **The item's own icon**, if the user attached one. It overrides everything —
//!    nobody is required to attach one, and the vast majority of items never will.
//! 2. **A host override.** Consulted against the *full host*, longest suffix first,
//!    before any reduction. This is the only way `console.aws.amazon.com` can resolve
//!    to AWS rather than to Amazon: one company runs distinct products under one
//!    registrable domain, and eTLD+1 cannot tell them apart.
//! 3. **The domain map**, keyed by registrable domain (eTLD+1) through the Public
//!    Suffix List. `https://app.example.co.uk/login?next=/x#y` and `example.co.uk`
//!    reduce to the same key, which is the point.
//! 4. **A generated geometric mark**, seeded from the same domain so it is stable
//!    across sessions and devices.
//!
//! Step 3 is eTLD+1 and not the raw host on purpose. `mail.google.com` and
//! `google.com` are one brand and must get one tile, or the list looks like two
//! unrelated accounts. It is the same reduction CLAUDE.md §4.8 requires for autofill
//! matching, where using `contains()` *"is the difference between a password manager
//! and a phishing accessory"* — so it is worth doing once, correctly, in a module both
//! can share.
//!
//! ## No initials
//!
//! The fallback used to be one or two letters on a coloured tile. It is a geometric
//! mark now: a monogram in a product full of real brand marks reads as a broken image,
//! and two letters carry no more information than a shape does — the item's name is
//! already on the row next to it.
//!
//! ## The map is data
//!
//! [`MAP_SOURCE`] is generated by `scripts/build-icon-map.ts` and compiled in.
//! Adding a brand is: drop the SVG into a source folder, run `pnpm icons:build`.
//! Removing one for a takedown is a rebuild after deleting a row. No code changes.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use serde::{Deserialize, Serialize};

/// Number of identity tones the token layer defines (`--identity-1` … `-7`).
pub const IDENTITY_TONES: u8 = 7;

/// The generated map, compiled into the binary.
///
/// Tab-separated, three kinds of row: `host` (matched against the full host before any
/// reduction), `domain` (eTLD+1) and `card` (ADD-001's non-domain namespace).
static MAP_SOURCE: &str = include_str!("../../assets/icon-map.tsv");

/// One bundled mark.
#[derive(Debug, Clone, PartialEq, Eq)]
struct Entry {
    /// File stem under `dist/icons/`.
    key: String,
    /// Whether `<key>-light.svg` and `<key>-dark.svg` also exist.
    themed: bool,
}

/// The parsed map, built once on first use.
struct IconMap {
    hosts: BTreeMap<String, Entry>,
    domains: BTreeMap<String, Entry>,
    cards: BTreeMap<String, Entry>,
}

fn map() -> &'static IconMap {
    static MAP: OnceLock<IconMap> = OnceLock::new();
    MAP.get_or_init(|| {
        let mut hosts = BTreeMap::new();
        let mut domains = BTreeMap::new();
        let mut cards = BTreeMap::new();

        for line in MAP_SOURCE.lines() {
            if line.starts_with('#') || line.trim().is_empty() {
                continue;
            }
            let mut parts = line.split('\t');
            let (Some(kind), Some(matcher), Some(key), Some(_source), Some(variant)) = (
                parts.next(),
                parts.next(),
                parts.next(),
                parts.next(),
                parts.next(),
            ) else {
                // A malformed row is skipped rather than fatal: a broken map must
                // degrade to generated shapes, not stop the app from opening a vault.
                continue;
            };
            let entry = Entry {
                key: key.to_owned(),
                themed: variant == "color+theme",
            };
            match kind {
                "host" => {
                    hosts.insert(matcher.to_ascii_lowercase(), entry);
                }
                "domain" => {
                    domains.insert(matcher.to_ascii_lowercase(), entry);
                }
                "card" => {
                    cards.insert(matcher.to_ascii_lowercase(), entry);
                }
                _ => {}
            }
        }

        IconMap {
            hosts,
            domains,
            cards,
        }
    })
}

/// How an item's tile should be drawn.
///
/// A closed enum rather than an optional key, because these are different renderings
/// and not one rendering with missing fields. A frontend holding `Option<String>` has
/// to decide what a `None` means; holding this, it cannot get it wrong.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", tag = "kind")]
pub enum Icon {
    /// A bundled SVG. The frontend loads `icons/<key>.svg`.
    Bundled {
        /// Key into the bundled set. Never a URL, never anything user-supplied.
        key: String,
        /// Whether `<key>-light.svg` / `<key>-dark.svg` exist for theme selection.
        themed: bool,
    },
    /// The user's own icon, stored encrypted in the item. Fetched by item id.
    Custom,
    /// A generated geometric mark.
    Shape {
        /// Drives which shape is drawn. Stable for a given identity, forever.
        seed: u32,
        /// Which `--identity-N` to build the mark from, `1..=IDENTITY_TONES`.
        tone: u8,
    },
}

/// The host of a URL, lowercased, with no reduction applied.
///
/// Returns `None` for an IP literal or anything unparseable — the same rejections
/// [`registrable_domain`] makes, because a host override must never match an address.
#[must_use]
pub fn host_of(raw: &str) -> Option<String> {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return None;
    }

    // A bare `example.com` is not a URL, and users type bare domains constantly.
    // Parsing with a scheme prepended is a formatting convenience, not a network
    // operation — nothing here connects to anything.
    let parsed = url::Url::parse(trimmed)
        .or_else(|_| url::Url::parse(&format!("https://{trimmed}")))
        .ok()?;

    if parsed
        .host()
        .is_some_and(|h| !matches!(h, url::Host::Domain(_)))
    {
        return None;
    }

    let host = parsed.host_str()?.trim_end_matches('.');
    if host.is_empty() {
        return None;
    }
    Some(host.to_ascii_lowercase())
}

/// The registrable domain (eTLD+1) of a URL, lowercased.
///
/// Returns `None` for anything without a public-suffix host — an IP address, a
/// `localhost`, an internal hostname, or free text someone typed into a URL field.
///
/// Exposed because §7.4's fix flow needs exactly this: it opens
/// `https://<etld+1>/.well-known/change-password` **in the browser** and must never
/// probe it from the app.
#[must_use]
pub fn registrable_domain(raw: &str) -> Option<String> {
    let host = host_of(raw)?;
    let suffix = psl::domain(host.as_bytes())?;
    let domain = std::str::from_utf8(suffix.as_bytes()).ok()?;
    Some(domain.to_ascii_lowercase())
}

/// A stable 32-bit hash. FNV-1a.
///
/// Not `DefaultHasher`: `std`'s hasher is explicitly not stable across releases, and a
/// tile that changes shape when the toolchain changes would look like data corruption
/// to a user who has learned to recognise their items by it. This is not a security
/// hash and does not need to be — it only has to be the same tomorrow, and on the other
/// machine the vault syncs to.
#[must_use]
fn fnv1a(input: &str) -> u32 {
    const OFFSET: u32 = 0x811c_9dc5;
    const PRIME: u32 = 0x0100_0193;

    let mut hash = OFFSET;
    for byte in input.as_bytes() {
        hash ^= u32::from(*byte);
        hash = hash.wrapping_mul(PRIME);
    }
    hash
}

/// Pick an identity tone from a string.
#[must_use]
pub fn tone_for(identity: &str) -> u8 {
    u8::try_from(fnv1a(identity) % u32::from(IDENTITY_TONES)).unwrap_or(0) + 1
}

/// The seed a generated mark is drawn from.
#[must_use]
pub fn seed_for(identity: &str) -> u32 {
    fnv1a(identity)
}

/// The bundled entry for a full host, checking longest suffix first.
///
/// `console.aws.amazon.com` tries the whole host, then `aws.amazon.com`, then
/// `amazon.com` — and stops at the first override. A plain domain hit is left to
/// [`lookup`] so the two namespaces stay separate.
fn lookup_host(host: &str) -> Option<&'static Entry> {
    let map = map();
    let mut candidate = host;
    loop {
        if let Some(entry) = map.hosts.get(candidate) {
            return Some(entry);
        }
        let (_, rest) = candidate.split_once('.')?;
        if rest.is_empty() {
            return None;
        }
        candidate = rest;
    }
}

/// The bundled entry for a registrable domain, if one is mapped.
#[must_use]
pub fn lookup(domain: &str) -> Option<&'static str> {
    map()
        .domains
        .get(&domain.to_ascii_lowercase())
        .map(|e| e.key.as_str())
}

/// How many domains the compiled map covers, for the diagnostics command.
#[must_use]
pub fn mapped_domain_count() -> usize {
    map().domains.len()
}

/// Resolve an item's tile.
///
/// The first URL with a usable host decides the identity, so the mark is stable when a
/// user adds a second URL to an existing item. With no usable URL the title is the
/// identity string — which means renaming an item can change its shape, and that is the
/// right trade: the alternative is storing a seed, which would be a new item field and
/// a migration for a decoration.
///
/// `has_custom` short-circuits everything: an icon the user chose outranks one we
/// guessed from a domain.
#[must_use]
pub fn resolve(urls: &[String], title: &str, has_custom: bool) -> Icon {
    if has_custom {
        return Icon::Custom;
    }

    for raw in urls {
        let Some(host) = host_of(raw) else { continue };
        if let Some(entry) = lookup_host(&host) {
            return Icon::Bundled {
                key: entry.key.clone(),
                themed: entry.themed,
            };
        }
        if let Some(domain) = registrable_domain(raw) {
            if let Some(entry) = map().domains.get(&domain) {
                return Icon::Bundled {
                    key: entry.key.clone(),
                    themed: entry.themed,
                };
            }
        }
    }

    let identity = urls
        .iter()
        .find_map(|u| registrable_domain(u))
        .unwrap_or_else(|| title.to_owned());
    Icon::Shape {
        seed: seed_for(&identity),
        tone: tone_for(&identity),
    }
}

/// Resolve a card tile from its brand, per ADD-001's `card:` namespace.
///
/// `brand` is derived from the card number by the caller, not from a domain, which is
/// why these cannot live in the domain map. Unlike [`resolve`] there is no title to fall
/// back to: a card with no recognised brand takes a mark seeded from the brand string,
/// so every unknown brand still gets a stable tile.
#[must_use]
pub fn resolve_card(brand: &str, has_custom: bool) -> Icon {
    if has_custom {
        return Icon::Custom;
    }
    let key = format!("card:{}", brand.to_ascii_lowercase());
    if let Some(entry) = map().cards.get(&key) {
        return Icon::Bundled {
            key: entry.key.clone(),
            themed: entry.themed,
        };
    }
    Icon::Shape {
        seed: seed_for(&key),
        tone: tone_for(&key),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── normalisation ────────────────────────────────────────────────────────
    //
    // The deep-link case is the one that matters most: an item saved from a browser
    // carries the whole URL, and if that does not reduce to the same key as the bare
    // domain the same service shows two different tiles.

    #[test]
    fn deep_links_reduce_to_the_same_domain_as_the_bare_host() {
        let expected = Some("example.co.uk".to_owned());
        assert_eq!(
            registrable_domain("https://app.example.co.uk/login?next=/settings#tab=2"),
            expected
        );
        assert_eq!(registrable_domain("example.co.uk"), expected);
        assert_eq!(registrable_domain("http://example.co.uk:8443/"), expected);
        assert_eq!(
            registrable_domain("https://user:pw@www.example.co.uk/x"),
            expected
        );
        assert_eq!(registrable_domain("HTTPS://WWW.EXAMPLE.CO.UK"), expected);
    }

    #[test]
    fn subdomains_of_any_depth_reduce() {
        for raw in [
            "https://a.b.c.d.example.com/",
            "www.example.com",
            "https://mail.example.com",
        ] {
            assert_eq!(
                registrable_domain(raw),
                Some("example.com".to_owned()),
                "{raw}"
            );
        }
    }

    #[test]
    fn multi_part_suffixes_keep_two_labels() {
        assert_eq!(
            registrable_domain("https://shop.amazon.co.uk"),
            Some("amazon.co.uk".to_owned())
        );
        assert_eq!(
            registrable_domain("https://foo.github.io"),
            Some("foo.github.io".to_owned())
        );
    }

    #[test]
    fn addresses_and_junk_have_no_domain() {
        for raw in [
            "",
            "   ",
            "localhost",
            "http://127.0.0.1:1420/",
            "https://[::1]/",
            "192.168.1.1",
            "not a url at all",
            "://///",
            "ftp://",
            "com",
        ] {
            assert_eq!(registrable_domain(raw), None, "{raw}");
        }
    }

    #[test]
    fn a_trailing_dot_is_the_same_host() {
        assert_eq!(
            registrable_domain("https://example.com./path"),
            Some("example.com".to_owned())
        );
    }

    // ── the locked mapping set ───────────────────────────────────────────────
    //
    // A guard on the *matching algorithm*, not on the data: the build script may change
    // how it infers, and this is what stops a change silently taking Google's mark off
    // Google or putting Amazon's on an AWS console login. Every pair here was checked by
    // hand against the source manifests.

    fn key_of(url: &str) -> Option<String> {
        match resolve(&[url.to_owned()], "unused", false) {
            Icon::Bundled { key, .. } => Some(key),
            Icon::Shape { .. } | Icon::Custom => None,
        }
    }

    #[test]
    fn known_domains_keep_their_brands() {
        let expected: &[(&str, &str)] = &[
            ("https://github.com/settings", "github"),
            ("https://www.google.com/", "google"),
            ("https://accounts.google.com/signin", "google"),
            ("https://youtube.com/feed", "youtube"),
            ("https://dashboard.stripe.com/payments", "stripe"),
            ("https://www.netflix.com/browse", "netflix"),
            ("https://open.spotify.com/", "spotify"),
            ("https://www.paypal.com/", "paypal"),
            ("https://www.linkedin.com/feed/", "linkedin"),
            ("https://www.amazon.com/", "amazon"),
            ("https://www.amazon.co.uk/", "amazon"),
            ("https://www.dropbox.com/home", "dropbox"),
            ("https://app.slack.com/client", "slack"),
            ("https://www.figma.com/files", "figma"),
            ("https://gitlab.com/dashboard", "gitlab"),
        ];
        for (url, key) in expected {
            assert_eq!(key_of(url).as_deref(), Some(*key), "{url}");
        }
    }

    #[test]
    fn aws_is_not_amazon() {
        // The case ADD-001's brief calls out by name. `console.aws.amazon.com` reduces
        // to `amazon.com`, so without the host override it would wear Amazon's mark.
        assert_eq!(
            key_of("https://console.aws.amazon.com/console/home").as_deref(),
            Some("aws")
        );
        assert_eq!(
            key_of("https://signin.aws.amazon.com/").as_deref(),
            Some("aws")
        );
        assert_eq!(
            key_of("https://www.amazon.com/gp/css/homepage.html").as_deref(),
            Some("amazon")
        );
    }

    #[test]
    fn google_and_youtube_are_distinct_brands() {
        assert_ne!(key_of("https://google.com"), key_of("https://youtube.com"));
    }

    #[test]
    fn an_unmapped_domain_gets_a_stable_shape_and_never_initials() {
        let a = resolve(
            &["https://not-a-real-brand-xyzzy.example/".to_owned()],
            "Whatever",
            false,
        );
        let b = resolve(
            &["https://not-a-real-brand-xyzzy.example/deep/link?q=1".to_owned()],
            "Whatever",
            false,
        );
        assert_eq!(a, b, "the same domain must always draw the same mark");
        assert!(matches!(a, Icon::Shape { .. }));
    }

    #[test]
    fn a_custom_icon_outranks_a_bundled_one() {
        assert_eq!(
            resolve(&["https://github.com".to_owned()], "GitHub", true),
            Icon::Custom
        );
    }

    #[test]
    fn card_brands_resolve_from_their_own_namespace() {
        for brand in ["visa", "mastercard", "amex"] {
            assert!(
                matches!(resolve_card(brand, false), Icon::Bundled { .. }),
                "{brand}"
            );
        }
    }

    #[test]
    fn the_compiled_map_is_not_empty() {
        // A build that emitted an empty map would make every test above fall through to
        // a shape and still "pass" if they only checked for stability.
        assert!(
            mapped_domain_count() > 1000,
            "map has {} domains",
            mapped_domain_count()
        );
    }

    #[test]
    fn tones_stay_inside_the_token_ramp() {
        for identity in ["a", "example.com", "", "zzzzzzzzzzzz", "🙂"] {
            let tone = tone_for(identity);
            assert!((1..=IDENTITY_TONES).contains(&tone), "{identity} -> {tone}");
        }
    }
}
