// SPDX-License-Identifier: AGPL-3.0-or-later
//! `NSPasteboard` with the concealed-type marker (SPEC-V1 §8).
//!
//! **UNVERIFIED PLATFORM (ADD-005).** Nothing in this file has ever been
//! compiled. Every signature below was read out of `objc2-app-kit 0.3.2`'s
//! generated bindings rather than recalled, but reading a signature is not
//! running the code. `MACOS-UNVERIFIED.md` lists what to check on hardware.
//!
//! macOS has no Clipboard History, but it has clipboard managers and Universal
//! Clipboard, and both will happily keep a password. The convention for opting
//! out is a pasteboard type that clipboard managers agree to ignore:
//!
//! - `org.nspasteboard.ConcealedType` — the identifier nspasteboard.org names
//!   for *"confidential or sensitive data on the general pasteboard"*.
//! - `org.nspasteboard.AutoGeneratedType` — marks the write as programmatic, so
//!   managers that record only user copies skip it.
//!
//! Neither is enforced by the OS the way the Windows formats are, which is worth
//! being honest about: on macOS this is a request that well-behaved software
//! honours, not a guarantee. The `changeCount` ownership check below *is* a real
//! guarantee, and it is what stops auto-clear destroying something the user
//! copied afterwards.
//!
//! **Why `declareTypes:owner:` and not `clearContents()`.** The convention needs
//! the concealed marker to be on the pasteboard *before* the password is, or a
//! manager reading in between records the password. Declaring all three types up
//! front closes that window structurally instead of relying on call ordering, and
//! it is also the form that is correct under the stricter reading of
//! `setString:forType:` — Apple documents the type as needing to be declared
//! first, and `clearContents()` alone does not declare anything.
//! `declareTypes:owner:` implicitly clears and returns the new change count, so it
//! replaces two calls with one.

use std::sync::atomic::{AtomicU64, Ordering};

use objc2_app_kit::{NSPasteboard, NSPasteboardType, NSPasteboardTypeString};
use objc2_foundation::{NSArray, NSData, NSString};

use crate::platform::clipboard::{Clipboard, ClipboardError};

/// The `AppKit` constant for plain-text pasteboard content.
///
/// Reading it is `unsafe` only because it is an `extern "C"` static; the value
/// is a framework-owned immutable `NSString` that exists for the lifetime of the
/// process. Wrapped here so the single access has one place to justify it,
/// rather than an `unsafe` block inline in the copy path.
fn pasteboard_type_string() -> &'static NSPasteboardType {
    // SAFETY: `NSPasteboardTypeString` is declared in `objc2-app-kit` as
    // `pub static NSPasteboardTypeString: &'static NSPasteboardType` inside an
    // `extern "C"` block. It is a constant exported by AppKit and initialised
    // before any Objective-C code can run, is never written to, and its lifetime
    // is the process's — so there is no race and no dangling reference.
    unsafe { NSPasteboardTypeString }
}

/// Respected by clipboard managers as "do not record this".
const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
/// Marks the write as programmatic rather than a user copy.
///
// UNVERIFIED: `ConcealedType` is quoted directly by nspasteboard.org;
// `AutoGeneratedType` is part of the same family but I could not confirm the exact
// spelling from a primary source — the site's own fetchable text names
// `ConcealedType` and `TransientType`. A wrong identifier here is silent: it
// declares a type nothing reads, and the *concealed* marker still does the
// security-relevant work. See MACOS-UNVERIFIED.md item C3.
const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

/// The real macOS pasteboard.
pub struct MacClipboard {
    last_write: AtomicU64,
}

impl MacClipboard {
    /// A handle to the general pasteboard.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            last_write: AtomicU64::new(0),
        }
    }
}

impl Default for MacClipboard {
    fn default() -> Self {
        Self::new()
    }
}

impl Clipboard for MacClipboard {
    fn set_secret(&self, value: &str) -> Result<u64, ClipboardError> {
        // `generalPasteboard` is generated as a safe `pub fn` returning
        // `Retained<NSPasteboard>`: objc2 owns the retain/release and the method
        // cannot return null.
        let pasteboard = NSPasteboard::generalPasteboard();

        let concealed = NSString::from_str(CONCEALED_TYPE);
        let auto_generated = NSString::from_str(AUTO_GENERATED_TYPE);
        // Markers first in the declaration order too — not because the order of a
        // declaration array is meaningful, but because a reader of this code
        // should see the same intent the comment above states.
        let types = NSArray::from_slice(&[
            &*concealed,
            &*auto_generated,
            pasteboard_type_string() as &NSString,
        ]);

        // SAFETY: `declareTypes_owner` is `unsafe` in the bindings solely because
        // `new_owner` is an untyped `Option<&AnyObject>` that AppKit will send
        // pasteboard-provider messages to. We pass `None`, so there is no owner to
        // message and no type-confusion to cause. `new_types` is a live
        // `NSArray<NSString>` that outlives the call.
        let change_count = unsafe { pasteboard.declareTypes_owner(&types, None) };

        // Empty data for the markers, matching nspasteboard.org's own sample
        // (`setData: [NSData data] forType: ...`). These are presence flags; a
        // clipboard manager checks whether the type exists, not what is in it.
        let empty = NSData::with_bytes(&[]);
        let concealed_written = pasteboard.setData_forType(Some(&empty), &concealed);
        let auto_written = pasteboard.setData_forType(Some(&empty), &auto_generated);
        if !concealed_written {
            // Fail closed (CLAUDE.md §4.10). If the concealed marker did not land,
            // a clipboard manager is free to record this password permanently, and
            // copying anyway would be the app quietly doing the thing §8 exists to
            // prevent. Better to refuse and tell the user than to leak silently.
            return Err(ClipboardError::WriteFailed);
        }
        // The auto-generated marker is advisory on top of the concealed one, so its
        // failure is not worth refusing a copy over.
        debug_assert!(auto_written, "the auto-generated marker did not land");

        let text = NSString::from_str(value);
        if !pasteboard.setString_forType(&text, pasteboard_type_string()) {
            return Err(ClipboardError::WriteFailed);
        }

        // `declareTypes:owner:` returns the change count its own clear produced,
        // which is the number `clear_if_ours` must later compare against. Taking it
        // from there rather than re-reading `changeCount()` avoids a race with
        // another process writing between our write and our read.
        let token = u64::try_from(change_count).unwrap_or(0);
        self.last_write.store(token, Ordering::SeqCst);
        Ok(token)
    }

    fn clear_if_ours(&self, token: u64) -> Result<bool, ClipboardError> {
        let pasteboard = NSPasteboard::generalPasteboard();
        let current = u64::try_from(pasteboard.changeCount()).unwrap_or(0);
        if current != token {
            // The user copied something else. Not ours to destroy.
            return Ok(false);
        }
        pasteboard.clearContents();
        Ok(true)
    }
}

/// The pasteboard types a secret write must carry, for the platform test.
#[must_use]
pub const fn concealed_types() -> [&'static str; 2] {
    [CONCEALED_TYPE, AUTO_GENERATED_TYPE]
}

/// Whether `pasteboard_type` is currently declared on the general pasteboard.
///
/// The macOS counterpart to `windows::clipboard::format_present`, and it exists
/// for the same reason: a `set_secret` that returned `Ok` is not evidence that the
/// concealed marker actually landed. Only a read-back is.
#[must_use]
pub fn type_present(pasteboard_type: &str) -> bool {
    let pasteboard = NSPasteboard::generalPasteboard();
    let wanted = NSString::from_str(pasteboard_type);
    let candidates = NSArray::from_slice(&[&*wanted]);
    pasteboard.availableTypeFromArray(&candidates).is_some()
}
