//! `NSPasteboard` with the concealed-type marker (SPEC-V1 §8).
//!
//! macOS has no Clipboard History, but it has clipboard managers and Universal
//! Clipboard, and both will happily keep a password. The convention for opting
//! out is a pasteboard type that clipboard managers agree to ignore:
//!
//! - `org.nspasteboard.ConcealedType` — the community convention respected by
//!   the common clipboard managers.
//! - `org.nspasteboard.AutoGeneratedType` — marks the write as programmatic, so
//!   managers that record only user copies skip it.
//!
//! Neither is enforced by the OS the way the Windows formats are, which is worth
//! being honest about: on macOS this is a request that well-behaved software
//! honours, not a guarantee. The `changeCount` ownership check below *is* a real
//! guarantee, and it is what stops auto-clear destroying something the user
//! copied afterwards.

use std::sync::atomic::{AtomicU64, Ordering};

use objc2_app_kit::{NSPasteboard, NSPasteboardType, NSPasteboardTypeString};
use objc2_foundation::NSString;

use crate::platform::clipboard::{Clipboard, ClipboardError};

/// The `AppKit` constant for plain-text pasteboard content.
///
/// Reading it is `unsafe` only because it is an `extern "C"` static; the value
/// is a framework-owned immutable `NSString` that exists for the lifetime of the
/// process. Wrapped here so the single access has one place to justify it,
/// rather than an `unsafe` block inline in the copy path.
fn pasteboard_type_string() -> &'static NSPasteboardType {
    // SAFETY: `NSPasteboardTypeString` is a constant exported by `AppKit` and
    // initialised before any Objective-C code can run. It is never written to,
    // so there is no data race, and its lifetime is the process's.
    unsafe { NSPasteboardTypeString }
}

/// Respected by clipboard managers as "do not record this".
const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
/// Marks the write as programmatic rather than a user copy.
const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

/// The real macOS pasteboard.
pub struct MacClipboard {
    last_write: AtomicU64,
}

impl MacClipboard {
    /// A handle to the general pasteboard.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            last_write: AtomicU64::new(0),
        }
    }
}

impl Default for MacClipboard {
    fn default() -> Self {
        Self::new()
    }
}

impl Clipboard for MacClipboard {
    fn set_secret(&self, value: &str) -> Result<u64, ClipboardError> {
        // objc2 models these as safe: the generated bindings own the retain and
        // release, and `generalPasteboard` cannot return null.
        let pasteboard = NSPasteboard::generalPasteboard();
        pasteboard.clearContents();

        // The markers first. A clipboard manager that reads the pasteboard
        // between the text landing and the marker landing would record the
        // password, and that window is avoidable simply by ordering the writes.
        let empty = NSString::from_str("");
        pasteboard.setString_forType(&empty, &NSString::from_str(CONCEALED_TYPE));
        pasteboard.setString_forType(&empty, &NSString::from_str(AUTO_GENERATED_TYPE));

        let text = NSString::from_str(value);
        if !pasteboard.setString_forType(&text, pasteboard_type_string()) {
            return Err(ClipboardError::WriteFailed);
        }
        let change_count = pasteboard.changeCount();

        let token = u64::try_from(change_count).unwrap_or(0);
        self.last_write.store(token, Ordering::SeqCst);
        Ok(token)
    }

    fn clear_if_ours(&self, token: u64) -> Result<bool, ClipboardError> {
        let pasteboard = NSPasteboard::generalPasteboard();
        let current = u64::try_from(pasteboard.changeCount()).unwrap_or(0);
        if current != token {
            // The user copied something else. Not ours to destroy.
            return Ok(false);
        }
        pasteboard.clearContents();
        Ok(true)
    }
}

/// The pasteboard types a secret write must carry, for the platform test.
#[must_use]
pub const fn concealed_types() -> [&'static str; 2] {
    [CONCEALED_TYPE, AUTO_GENERATED_TYPE]
}
