//! `NSPasteboard` with the concealed-type marker (SPEC-V1 §8).
//!
//! macOS has no Clipboard History, but it has clipboard managers and Universal
//! Clipboard, and both will happily keep a password. The convention for opting
//! out is a pasteboard type that clipboard managers agree to ignore:
//!
//! - `org.nspasteboard.ConcealedType` — the community convention respected by
//!   the common clipboard managers.
//! - `org.nspasteboard.AutoGeneratedType` — marks the write as programmatic, so
//!   managers that record only user copies skip it.
//!
//! Neither is enforced by the OS the way the Windows formats are, which is worth
//! being honest about: on macOS this is a request that well-behaved software
//! honours, not a guarantee. The `changeCount` ownership check below *is* a real
//! guarantee, and it is what stops auto-clear destroying something the user
//! copied afterwards.

use std::sync::atomic::{AtomicU64, Ordering};

use objc2_app_kit::NSPasteboard;
use objc2_foundation::{NSString, NSStringPboardType};

use crate::platform::clipboard::{Clipboard, ClipboardError};

/// Respected by clipboard managers as "do not record this".
const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
/// Marks the write as programmatic rather than a user copy.
const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";

/// The real macOS pasteboard.
pub struct MacClipboard {
    last_write: AtomicU64,
}

impl MacClipboard {
    /// A handle to the general pasteboard.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            last_write: AtomicU64::new(0),
        }
    }
}

impl Default for MacClipboard {
    fn default() -> Self {
        Self::new()
    }
}

impl Clipboard for MacClipboard {
    fn set_secret(&self, value: &str) -> Result<u64, ClipboardError> {
        // SAFETY: `generalPasteboard` returns the process-wide pasteboard and
        // never null on a running AppKit app. `clearContents` invalidates the
        // previous contents and returns the new change count. `setString_forType`
        // copies the string, so neither temporary needs to outlive the call.
        let change_count = unsafe {
            let pasteboard = NSPasteboard::generalPasteboard();
            pasteboard.clearContents();

            // The markers first: a manager that reads the pasteboard between the
            // text landing and the marker landing would record the password.
            let empty = NSString::from_str("");
            pasteboard.setString_forType(&empty, &NSString::from_str(CONCEALED_TYPE));
            pasteboard.setString_forType(&empty, &NSString::from_str(AUTO_GENERATED_TYPE));

            let text = NSString::from_str(value);
            if !pasteboard.setString_forType(&text, NSStringPboardType) {
                return Err(ClipboardError::WriteFailed);
            }
            pasteboard.changeCount()
        };

        let token = u64::try_from(change_count).unwrap_or(0);
        self.last_write.store(token, Ordering::SeqCst);
        Ok(token)
    }

    fn clear_if_ours(&self, token: u64) -> Result<bool, ClipboardError> {
        // SAFETY: as above; `changeCount` and `clearContents` have no
        // preconditions beyond a valid pasteboard.
        unsafe {
            let pasteboard = NSPasteboard::generalPasteboard();
            let current = u64::try_from(pasteboard.changeCount()).unwrap_or(0);
            if current != token {
                // The user copied something else. Not ours to destroy.
                return Ok(false);
            }
            pasteboard.clearContents();
        }
        Ok(true)
    }
}

/// The pasteboard types a secret write must carry, for the platform test.
#[must_use]
pub const fn concealed_types() -> [&'static str; 2] {
    [CONCEALED_TYPE, AUTO_GENERATED_TYPE]
}
